# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-22 19:46
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Note',
            new_name='Txt',
        ),
    ]
